config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'

  resources :therapists, only: [:index, :show, :edit, :update] do
    resources :sessions, only: [:new, :create]
    resources :messages, only: [:new, :create]
  end
  resources :sessions, only: [:show, :edit, :update, :delete] do
    resources :notes, only: [:new, :create]
  end
  resources :articles, only: [:index, :show]
  get '/dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :sessions
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :patient, class_name: 'User'
  belongs_to :therapist, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :therapist_bookings, class_name: 'Booking', foreign_key: 'therapist_id'
  has_many :patient_bookings, class_name: 'Booking', foreign_key: 'patient_id'

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_session, only: %i[show update]
  def index
    @applied_sessions = current_user.sessions
    @received_sessions = current_user.received_sessions
  end

  def show
  end

  def new
    @session = Session.new
    @therapist = User.find(params[:therapist_id])
  end

  def create
    @session = Session.new(session_params)
    patient = current_user
    @therapist = User.find(params[:therapist_id])
    @session.patient = patient
    @session.therapist = @therapist
    @session.status = 'pending'
    if @session.save
      redirect_to root_path, notice: 'Booked successfully.'
    else
      render :new
    end
  end

  private

  def session_params
    params.require(:session).permit(:date, :time)
  end

  def find_session
    @session = Session.find(params[:id])
  end
end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController
  def index
    @therapists = User.where(is_therapist: true)
  end

  def show
    @therapist = User.find(params[:id])
    @session = Session.new
  end

  private

  def therapist_paramas
    params.require(:therapist).permit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/views/therapists/index.html.erb
<div class="container therapists_index">
  <h1>Browse our therapists</h1>
  <div class="therapists_main">
    <% @therapists.each do |therapist| %>
      <div class="therapists_cards">
        <div class="therapist_card">
          <%= cl_image_tag therapist.photo.key, class:"card__img" %>
          <div class="therapist_card_info">
            <h4 class="therapists_card__header">Dr. <%= therapist.first_name %> <%= therapist.last_name %></h4>
            <p class="therapists_card__text">This is a therapist. This is a therapist. This is a therapist</p>
            <%= link_to 'View full profile', therapist_path(therapist), class: 'therapists_btn' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back', root_path, class: 'button'%>
</div>

app/views/therapists/show.html.erb
<div class='show-card'>
  <h1>Dr. <%=@therapist.first_name %> <%= @therapist.last_name %></h1>
  <img src='#' alt='Therapist image'>
  <h3><%= @therapist.area_of_expertise %></h3>
  <div class='show-info'>
    <h3>Little about me</h3>
    <p><%= @therapist.description %></p>
  </div>
</div>
<div class='show-links'>
  <p><%= link_to "Book new session",  new_therapist_session_path(@therapist) %></p>
  <p><%= link_to "Message",  new_therapist_message_path(@therapist) %></p>
  <p><%= link_to "Back", therapists_path %></p>
</div>